### ISSUE TITLE
Error when installing the extension

### ISSUE THREAD

**Issue by rebaz88** [tastyigniter/ti-ext-payregister#1]
Hello 
I am new to tastyigniter. I get this error when I try to install Payregister 
tastyigniter/flame: ~1.0,
Laravel: 5.8

"Declaration of Symfony\Component\HttpFoundation\ResponseHeaderBag::set(string $key, $values, bool $replace = true) should be compatible with Symfony\Component\HttpFoundation\HeaderBag::set($key, $values, $replace = true)" on line 293 of /Users/rebaz/Sites/restaurant/extensions/igniter/payregister/vendor/symfony/http-foundation/ResponseHeaderBag.php#0 /Users/rebaz/Sites/restaurant/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Declaration of ...', '/Users/rebaz/Si...', 293, Array) #1 /Users/rebaz/Sites/restaurant/vendor/composer/ClassLoader.php(444): include() #2 /Users/rebaz/Sites/restaurant/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/rebaz/Si...') #3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...') #4 /Users/rebaz/Sites/restaurant/extensions/igniter/payregister/vendor/symfony/http-foundation/Response.php(196): spl_autoload_call('Symfony\\Compone...') #5 /Users/rebaz/Sites/restaurant/extensions/igniter/payregister/vendor/symfony/http-foundation/JsonResponse.php(44): Symfony\Component\HttpFoundation\Response->__construct('', 200, Array) #6 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 200, Array) #7 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(746): Illuminate\Http\JsonResponse->__construct(Array) #8 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Array) #9 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Array) #10 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #11 /Users/rebaz/Sites/restaurant/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(23): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #12 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure)) #13 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #14 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #15 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #16 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #17 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #18 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #19 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #20 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #21 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #22 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #23 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #24 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #25 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #26 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #27 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #28 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #29 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #30 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #31 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #32 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #33 /Users/rebaz/Sites/restaurant/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #34 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request)) #35 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #36 /Users/rebaz/Sites/restaurant/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #37 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Setting\Middleware\SaveSetting->handle(Object(Illuminate\Http\Request), Object(Closure)) #38 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #39 /Users/rebaz/Sites/restaurant/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #40 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure)) #41 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #42 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #43 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #44 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #45 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #46 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure)) #47 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #48 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #49 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #50 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #51 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #52 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #53 /Users/rebaz/Sites/restaurant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #54 /Users/rebaz/Sites/restaurant/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #55 /Users/rebaz/.composer/vendor/laravel/valet/server.php(158): require('/Users/rebaz/Si...') #56 {main}

**Comment by sampoyigi** [comment]
Try upgrading your PHP to 7.2+
