### ISSUE TITLE
Blank order statuses

### ISSUE THREAD

**Issue by ryanmitchell** [tastyigniter/ti-ext-payregister#15]
At the moment when a payment fails (or is a duplicate) the order status is left blank, so the order appears in the admin list without a status which can be confusing for staff using it.

Should we look to implement a default status of 'failed' or 'incomplete' which is then made into 'received' or whatever is chosen on the payment gateway when a payment is successful.

**Comment by sampoyigi** [comment]
How about we use the configured **Cancellation Order Status** in settings?

**Comment by ryanmitchell** [comment]
Yep that works - are you happy with the principle - somewhere in cart/OrderManager/saveOrder() we set that status?

**Comment by sampoyigi** [comment]
Erm.. it should be the payment class handling/deciding what status to set when a payment is cancelled or fails and an incomplete order should always have a blank status.

**Comment by sampoyigi** [comment]
See these changes to display blank order status as Incomplete tastyigniter/TastyIgniter@46e814362e81575e9abf880463565a2823b50da4

**Comment by ryanmitchell** [comment]
That should be enough I think - as long as its not blank in the admin it shouldn't cause confusion
