### ISSUE TITLE
[Help on PR] Generete automatically partials for enabled payments after child theme is created.

### ISSUE THREAD

**Issue by BreakSecurity** [tastyigniter/ti-ext-payregister#19]
As discussed here:
https://forum.tastyigniter.com/d/2293-payment

Please point me in the right direction. Part of the code to edit, examples of similar code, etc...

**Comment by sampoyigi** [comment]
You can start with this within the payregister/Extension file, let me know if you need me to explain what the code does ;)

```
public function boot()
{
    Themes_model::extend(function ($model) {
        $model->bindEvent('model.afterSave', function () use ($model) {
            if (!$model->wasRecentlyCreated)
                return;

            // Logic here.
        });
    });
}
```

**Comment by BreakSecurity** [comment]
Is this be done here? https://github.com/tastyigniter/ti-ext-payregister/blob/a0509e053600140886484e7e2d309590341bbd00/Extension.php#L71

**Comment by sampoyigi** [comment]
Yup

**Comment by BreakSecurity** [comment]
Closing since now it is merged
