### ISSUE TITLE
Authorize.net Issue 

### ISSUE THREAD

**Issue by Pugy365** [tastyigniter/ti-ext-payregister#20]
**Expected behavior:*
Authorize.net pop up at checkout when confirming order so customer can enter there credit card information. 

**Actual behavior:*

No authorize.net pop up at checkout, I get below error. 

Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getTrack1() on null
in /var/www/the-diamond.com/public_html/extensions/igniter/payregister/vendor/omnipay/authorizenet/src/Message/AIMAuthorizeRequest.php:69
Stack trace:
#0 /var/www/the-diamond.com/public_html/extensions/igniter/payregister/vendor/omnipay/authorizenet/src/Message/AIMAuthorizeRequest.php(35): Omnipay\AuthorizeNet\Message\AIMAuthorizeRequest->addPayment(Object(SimpleXMLElement))
#1 /var/www/the-diamond.com/public_html/extensions/igniter/payregister/vendor/omnipay/common/src/Common/Message/AbstractRequest.php(686): Omnipay\AuthorizeNet\Message\AIMAuthorizeRequest->getData()
#2 /var/www/the-diamond.com/public_html/extensions/igniter/payregister/payments/AuthorizeNetAim.php(92): Omnipay\Common\Message\AbstractRequest->send()
#3 [internal function]: Igniter\PayRegister\Payments\AuthorizeNetAim->processPaymentForm(Array, Object(Admin\Models\Payments_model), Object(Igniter\Cart\Models\Orders_model))
#4 /var/www/the-diamond.com/public_html/vendor/tastyigniter/flame/src/Traits/ExtendableTrait.php(428): call_user_func_array(Array, Array)
#5 /var/www/the-diamond.com/public_html/vendor/tastyigniter/flame/src/Database/Model.php(635): Igniter\Flame\Database\Model->extendableCall('processPaymentF...', Array)
#6 /var/www/the-diamond.com/public_html/extensions/igniter/cart/classes/OrderManager.php(227): Igniter\Flame\Database\Model->__call('processPaymentF...', Array)
#7 /var/www/the-diamond.com/public_html/extensions/igniter/cart/components/Checkout.php(199): Igniter\Cart\Classes\OrderManager->processPayment(Object(Igniter\Cart\Models\Orders_model), Array)
#8 /var/www/the-diamond.com/public_html/app/system/classes/BaseComponent.php(135): Igniter\Cart\Components\Checkout->onConfirm()
#9 /var/www/the-diamond.com/public_html/app/main/classes/MainController.php(408): System\Classes\BaseComponent->runEventHandler('onConfirm')
#10 /var/www/the-diamond.com/public_html/app/main/classes/MainController.php(361): Main\Classes\MainController->runHandler('checkout::onCon...')
#11 /var/www/the-diamond.com/public_html/app/main/classes/MainController.php(251): Main\Classes\MainController->processHandlers()
#12 /var/www/the-diamond.com/public_html/app/main/classes/MainController.php(192): Main\Classes\MainController->runPage(Object(Main\Template\Page))
#13 /var/www/the-diamond.com/public_html/app/system/classes/Controller.php(85): Main\Classes\MainController->remap('checkout')
#14 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): System\Classes\Controller->run('checkout')
#15 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#16 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(System\Classes\Controller), 'run')
#17 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#18 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#19 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/the-diamond.com/public_html/vendor/tastyigniter/flame/src/Currency/Middleware/CurrencyMiddleware.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Currency\Middleware\CurrencyMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/the-diamond.com/public_html/extensions/igniter/cart/middleware/CartMiddleware.php(12): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Cart\Middleware\CartMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/the-diamond.com/public_html/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#41 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#42 /var/www/the-diamond.com/public_html/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#43 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#44 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/the-diamond.com/public_html/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Setting\Middleware\SaveSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/the-diamond.com/public_html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/the-diamond.com/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 /var/www/the-diamond.com/public_html/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#59 {main}

**Reproduce steps:**
Every time when choosing Credir Card at checkout of order. Cash option works fine. 

**Version:**
TastIgniter v3.0.4-beta.24.4

**Additional Information:**
(Additional information, if any)

**Comment by sampoyigi** [comment]
Not reproducible in the latest release. Please reopen this issue if it still occurs, with a set of reproducible steps.
