### ISSUE TITLE
Stripe card fields should be translatable

### ISSUE THREAD

**Issue by pablogfb** [tastyigniter/ti-ext-payregister#24]
**Expected behavior:**
Stripe fields language should be elegible
**Actual behavior:**
Those fields are always in EN

assets/process.stripe.js[22] adding locale as an option works. for example:
`this.stripe = Stripe(this.options.publishableKey, {locale: 'es'})`

It might be added in the payment method settings

**Comment by ryanmitchell** [comment]
This has been implemented
