### ISSUE TITLE
How I can add a new payment gateway?

### ISSUE THREAD

**Issue by YnievesDotNet** [tastyigniter/ti-ext-payregister#25]
**Expected behavior:**
Add new Payment Gateway to my instance

**Actual behavior:**
I make a new extension but i get error with guzzle, maybe error on version.

**Reproduce steps:**
Install my own extension and try checkout one order

**Version:**
3.0.5

**Additional Information:**
Log attached
[SPOILER_message.txt](https://github.com/tastyigniter/ti-ext-payregister/files/6844473/SPOILER_message.txt)

**Comment by JamesThanna** [comment]
Can you paste the error here we we can help?

**Comment by JamesThanna** [comment]
Hard to say what exactly happened but I can guess it's to do with the request your making as Guzzle works fine for me with HTTP requests being made from the same version of TI. The error is stating that the method being called is not defined "chooseHandler()"

Can you provide the exact code being used removing any key's your using?

**Comment by YnievesDotNet** [comment]
i found error on guzzle version used. I change to version guzzle6 and now work fine, thanks.
