### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ricardochen** [tastyigniter/ti-ext-payregister#32]
### What happened?

Trying to create new payment method but its not updating the payment list, also removed existing ones in Extension.php and it stills shows.

Is there a cache somewhere that needs to be cleared?

public function registerPaymentGateways()
    {
        return [
            'Igniter\PayRegister\Payments\yappi' => [
                'code' => 'yappi',
                'name' => 'Yappi',
                'description' => 'Pague con Yappi de banco general',
            ],
            'Igniter\PayRegister\Payments\Cod' => [
                'code' => 'cod',
                'name' => 'lang:igniter.payregister::default.cod.text_payment_title',
                'description' => 'lang:igniter.payregister::default.cod.text_payment_desc',
            ],
            'Igniter\PayRegister\Payments\PaypalExpress' => [
                'code' => 'paypalexpress',
                'name' => 'lang:igniter.payregister::default.paypal.text_payment_title',
                'description' => 'lang:igniter.payregister::default.paypal.text_payment_desc',
            ],
            'Igniter\PayRegister\Payments\AuthorizeNetAim' => [
                'code' => 'authorizenetaim',
                'name' => 'lang:igniter.payregister::default.authorize_net_aim.text_payment_title',
                'description' => 'lang:igniter.payregister::default.authorize_net_aim.text_payment_desc',
            ],
            'Igniter\PayRegister\Payments\Stripe' => [
                'code' => 'stripe',
                'name' => 'lang:igniter.payregister::default.stripe.text_payment_title',
                'description' => 'lang:igniter.payregister::default.stripe.text_payment_desc',
            ],
            'Igniter\PayRegister\Payments\Mollie' => [
                'code' => 'mollie',
                'name' => 'lang:igniter.payregister::default.mollie.text_payment_title',
                'description' => 'lang:igniter.payregister::default.mollie.text_payment_desc',
            ],
            'Igniter\PayRegister\Payments\Square' => [
                'code' => 'square',
                'name' => 'lang:igniter.payregister::default.square.text_payment_title',
                'description' => 'lang:igniter.payregister::default.square.text_payment_desc',
            ],
        ];
    }

### What did you expect to happen?

New payment method listed

### Version

3.0.6

### What browser are you seeing the problem on?

Chrome

**Comment by ricardochen** [comment]
Nevermind,  did not use a Capital letter.

**Comment by ryanmitchell** [comment]
I would strongly suggest you register your new one through your own extension rather than adding it as part of pay register. This will prevent the need to make changes every update.
