### ISSUE TITLE
[Bug]: Payment error -> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constrain

### ISSUE THREAD

**Issue by niyonx** [tastyigniter/ti-ext-payregister#36]
### What happened?

I get this when using order approver to accept orders. I then see MISSING STRIPE INTENT ID.

I check the payment attempts for the order and I see this error. It seems the payment was not captured.

I have multi vendor with stripe connect, my stripe payment settings is set to authorization only and my stripe connect is set to destination charges.

### What did you expect to happen?

I expected the order to be captured successfully. Unfortunately, I can't find more logs of the error. This is the message stored in the payment logs of the database.

### Version

3.2.x

**Comment by niyonx** [comment]
Payment error -> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constrain also happens especially when I checkout being a guest

**Comment by ryanmitchell** [comment]
Ah I think this might be more of a multi vendor issue then - I did wonder why i couldn't replicate it. That was a crucial bit of missing information :)

@sampoyigi - one for you I think

**Comment by ryanmitchell** [comment]
I've updated the stripe authorise extension (1.1.2) to not throw this error when the intent id is not found which removes the error.

However, you getting this error does make me think your set up is incorrect as it was unable to find a payment requiring capture.

**Comment by niyonx** [comment]
@ryanmitchell hey Ryan, sam solved it by changing line 119 of the coupon history model. Changing 0 to null. Check it out and let us know!

This was the whole error message.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ti_db_dev`.`ti_igniter_coupons_history`, CONSTRAINT `ti_igniter_coupons_history_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `ti_customers` (`customer_id`) ON DELETE SET NULL O) (SQL: insert into `ti_igniter_coupons_history` (`order_id`, `customer_id`, `coupon_id`, `code`, `amount`, `min_total`, `updated_at`, `created_at`) values (286, 0, 5, 50% off, -29.99, 0, 2022-02-04 14:02:57, 2022-02-04 14:02:57))"

**Comment by ryanmitchell** [comment]
Great, glad you sorted it.
