### ISSUE TITLE
[Bug]: Saving Payment Method (Stripe) returns error

### ISSUE THREAD

**Issue by myrsk** [tastyigniter/ti-ext-payregister#37]
### What happened?

Getting an error when saving the stripe payment method in the admin side after placing my stripe keys (or even if it is left empty), same with other payment gateways too.

BadMethodCallException: Call to undefined method Admin\Models\Payments_model::getConfigAttributes()
in /home/username/domains/domain.com/public_html/order/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71

Appreciate your help on this. Thanks 🙂

### What did you expect to happen?

To be able to save without error, and enable stripe

### Version

3.2.x

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
BadMethodCallException: Call to undefined method Admin\Models\Payments_model::getConfigAttributes()
in /home/username/domains/domain.com/public_html/order/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71
```

**Comment by sampoyigi** [comment]
Fixed https://github.com/tastyigniter/TastyIgniter/commit/1da4091b58b8fef9104dda02fe33c19a087de004
